spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ragdb
    username: postgres
    password: postgres

  ai:
    openai:
      api-key: ${API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE